### @Scotland2025.Api_HostAddress = https://localhost:7243/api
### @Scotland2025.Api_HostAddress = https://localhost:7244/api
@Scotland2025.Api_HostAddress = http://localhost:5054/api


GET {{Scotland2025.Api_HostAddress}}/test/
Accept: application/json

###

GET {{Scotland2025.Api_HostAddress}}/images/
Accept: application/json

###
GET {{Scotland2025.Api_HostAddress}}/images/1
Accept: application/json

###
POST {{Scotland2025.Api_HostAddress}}/images
Content-Type: application/json
{
  "url": "https://hosting.photobucket.com/71031e7a-93a0-48c1-8371-0e82ef5324a5/6c82f9cd-fc22-4d10-bf76-465d969bfeaf.jpeg?width=180&height=180&fit=bounds"
}

###
PUT {{Scotland2025.Api_HostAddress}}/images/2
Content-Type: application/json
{
  "url": "testUrl",
  "description": "test desc",
  "dateAdded": "2023-10-01T00:00:00Z",
  "addedBy": "TestUser"
}

###
DELETE {{Scotland2025.Api_HostAddress}}/images/2
